#include <stdint.h>
#include QMK_KEYBOARD_H
#include "thock.h"

const char *keycode_to_name(uint16_t keycode) {
    switch (keycode) {
        case KC_A:
            return "A";
        case KC_B:
            return "B";
        case KC_C:
            return "C";
        case KC_D:
            return "D";
        case KC_E:
            return "E";
        case KC_F:
            return "F";
        case KC_G:
            return "G";
        case KC_H:
            return "H";
        case KC_I:
            return "I";
        case KC_J:
            return "J";
        case KC_K:
            return "K";
        case KC_L:
            return "L";
        case KC_M:
            return "M";
        case KC_N:
            return "N";
        case KC_O:
            return "O";
        case KC_P:
            return "P";
        case KC_Q:
            return "Q";
        case KC_R:
            return "R";
        case KC_S:
            return "S";
        case KC_T:
            return "T";
        case KC_U:
            return "U";
        case KC_V:
            return "V";
        case KC_W:
            return "W";
        case KC_X:
            return "X";
        case KC_Y:
            return "Y";
        case KC_Z:
            return "Z";
        case KC_1:
            return "1";
        case KC_2:
            return "2";
        case KC_3:
            return "3";
        case KC_4:
            return "4";
        case KC_5:
            return "5";
        case KC_6:
            return "6";
        case KC_7:
            return "7";
        case KC_8:
            return "8";
        case KC_9:
            return "9";
        case KC_0:
            return "0";
        case KC_ESC:
            return "ESC";
        case KC_TAB:
            return "TAB";
        case KC_ENTER:
            return "ENTER";
        case KC_SPACE:
            return "SPCE";
        case KC_BSPC:
            return "BSPCE";
        case KC_DEL:
            return "DLT";
        case KC_LEFT:
            return "LEFT";
        case KC_RIGHT:
            return "RIGHT";
        case KC_UP:
            return "UP";
        case KC_LGUI:
            return "LGUI";
        case KC_GRV:
            return "~";
        case KC_BSLS:
            return "BSLSH";
        case KC_DOWN:
            return "DOWN";
        case KC_LSFT:
            return "LSHFT";
        case KC_RSFT:
            return "RSHFT";
        case KC_LCTL:
            return "LCTRL";
        case KC_RCTL:
            return "RCTRL";
        case KC_LALT:
            return "LALT";
        case KC_RALT:
            return "RALT";
        case KC_CAPS:
            return "CAPS";
        case KC_MUTE:
            return "MUTE";
        case KC_PGUP:
            return "PGUP";
        case KC_PGDN:
            return "PGDN";
        case KC_HOME:
            return "HOME";
        case KC_END:
            return "END";
        case KC_INS:
            return "INSRT";
        case KC_F1:
            return "F1";
        case KC_F2:
            return "F2";
        case KC_F3:
            return "F3";
        case KC_F4:
            return "F4";
        case KC_F5:
            return "F5";
        case KC_F6:
            return "F6";
        case KC_F7:
            return "F7";
        case KC_F8:
            return "F8";
        case KC_F9:
            return "F9";
        case KC_F10:
            return "F10";
        case KC_F11:
            return "F11";
        case KC_F12:
            return "F12";
        case KC_PAUSE:
            return "XLEAD";
        // Add more keycodes as needed
        default:
            return "UNK";
    }
}
